version: "3.2"
services:
  ibizpms-app-mob:
    image: registry.cn-shanghai.aliyuncs.com/ibizsys/ibizpms-app-mob:latest
    ports:
      - "22120:22120"
    networks:
      - agent_network
    environment:
      - SPRING_CLOUD_NACOS_DISCOVERY_IP=172.16.240.110
      - SERVER_PORT=22120
      - SPRING_CLOUD_NACOS_DISCOVERY_SERVER-ADDR=172.16.240.110:8849
      - SPRING_REDIS_HOST=172.16.240.110
      - SPRING_REDIS_PORT=6380
      - SPRING_REDIS_DATABASE=0
      - SPRING_DATASOURCE_USERNAME=zentao
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_DATASOURCE_URL=jdbc:mysql://172.16.180.217:3306/zentao?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useOldAliasMetadataBehavior=true&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=com.mysql.jdbc.Driver
      - SPRING_DATASOURCE_DEFAULTSCHEMA=zentao
      - IBIZ_AUTH_LADP=true
      - JOBS_ADMINNAME=admin
      - JOBS_ADMIN-ADDRESS=http://172.16.240.110:10001
      - NACOS=172.16.240.110:8849
      - JOBS_ADMINPASSWORD=123456
      - JOBS_APP-NAME=ibzpms
      - ZUUL_ROUTES_IBZEMP_SERVICEID=pms-webapi
      - JOBS_APP-PORT=9998
      - JOBS_APP-IP=172.16.240.110
      - CAS=https://passport.ibizlab.cn
    deploy:
      resources:
           limits:
               memory: 800M
           reservations:
               memory: 400M    
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
    volumes:
      - "nfs:/app/file"

volumes:
  nfs:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=172.16.240.109,rw"
      device: ":/nfs"

networks:
  agent_network:
    driver: overlay
    attachable: true

